name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Maven Package
      run: mvn package
    - name: install node dependencies
      if: always()
      run: make node_modules
    - name: ESLint Validate
      if: always()
      run: cd src/main/react && npx eslint src/**/*.js
    - name: Check ReactJS Formatting
      if: always()
      run: diff -u <(cat src/main/react/src/**/*.js) <(cd src/main/react && npx prettier src/**/*.js)
    - name: Check Java Formatting
      if: always()
      run: diff -u <(cat src/main/java/com/google/sps/servlets/*.java) <(node_modules/clang-format/bin/linux_x64/clang-format --style=Google src/main/java/com/google/sps/servlets/*.java)
    - name: Notify On Failure
      if: failure()
      run: echo 'run "make validate" and "make pretty" to see/fix errors locally'